[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketioxide = { version = "0.10.0", features = ["state"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = "1.0.195"
serde_json = "1.0.111"
chrono = { version = "0.4.31", features = ["serde"] }
mongodb = "2.8.0"
thiserror = "1.0.61"
async-trait = "0.1.77"
database = { path = "../database" }