[package]
name = "chat-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
# serde 
serde = "1.0.195"
serde_json = "1.0.111"
chrono = { version = "0.4.31", features = ["serde"] }
mongodb = "2.8.0"
axum = "0.7"
thiserror = "1.0.61"
mockall = "0.12.1"
database = { path = "../database" }
reqwest = { version = "0.12.5", features = ["json"] }

